### ISSUE TITLE
I cant install it in windows

### ISSUE THREAD

**Issue by joseCocodin** [kevoj/redis-jwt#1]
[2017-12-12T08_35_32_435Z-debug.log](https://github.com/kevoj/redis-jwt/files/1550767/2017-12-12T08_35_32_435Z-debug.log)

**Comment by bytesleo** [comment]
Hi, I think that the error can occur due to some windows packages that are not properly configured, you can try that: 
```bash
npm install --global --production windows-build-tools
```
Note: similarly it would be very useful to have a terminal screen npm
